package nl.yogh.aerius.builder.domain;

public enum ServiceType {
  CALCULATOR_WUI, CALCULATOR_DATABASE,

  SCENARIO_WUI, SCENARIO_DATABASE,

  REGISTER_WUI, REGISTER_DATABASE, REGISTER_GEOSERVER,

  SCENARIO_BASE_GEOSERVER,

  TASKMANAGER, WORKER_OPS, WORKER_SRM,

  MONITOR_DATABASE,

  CONNECT, CONNECT_DATABASE,

  MELDING;
}
