package nl.yogh.aerius.builder.domain;

public enum ServiceType {
  CALCULATOR_WUI, CALCULATOR_DATABASE, CALCULATOR_GEOSERVER,

  REGISTER_WUI, REGISTER_DATABASE, REGISTER_GEOSERVER,

  SCENARIO_WUI, SCENARIO_DATABASE, SCENARIO_GEOSERVER,

  TASKMANAGER, WORKER_OPS, WORKER_SRM, WORKER_CALCULATE, WORKER_IMPORT,

  MONITOR_DATABASE,

  CONNECT, CONNECT_DATABASE,

  MELDING;
}
