FROM ubuntu:16.04

RUN apt update \
    && apt install -y wget

RUN mkdir ~/bin \
    && cd bin
    && wget http://ftp.tudelft.nl/apache/tomcat/tomcat-9/v9.0.2/bin/apache-tomcat-9.0.2.tar.gz \
    && tar -xzf /tmp/apache-tomcat-9.0.2.tar.gz
   && mv apache-tomcat-9.0.2.tar.gz tomcat

RUN tomcat/bin/startup.sh

